# This action runs on a local github runner
# See https://jano.dev/programming/2022/04/15/local-spm-ga.html

# To install xcpretty run:
# brew install ruby
# echo 'export PATH="/opt/homebrew/opt/ruby/bin:$PATH"' >> ~/.zshrc
# brew install xcpretty

name: Swift
on: [push]
jobs:
  ios-latest:
    name: Unit Tests (iOS 16.2, Xcode 14.2)
    runs-on: [self-hosted, X64, macOS]
    env: 
      DEVELOPER_DIR: /Applications/Xcode.app/Contents/Developer
    steps:
      - uses: actions/checkout@v3
      - name: Build iOS
        run: |
          set -o pipefail && xcodebuild test -scheme "OpenAIClient" -destination "OS=16.2,name=iPhone 14 Pro" | xcpretty
      - name: Build macOS
        run: |
          set -o pipefail && xcodebuild test -scheme "OpenAIClient" -destination "platform=macOS,arch=arm64" | xcpretty

    steps:
      - uses: actions/checkout@v3
      - name: Build iOS
        run: |
          set -o pipefail && xcodebuild test -scheme "OpenAIClient" -destination "OS=16.2,name=iPhone 14 Pro" -skipPackagePluginValidation | xcpretty
      - name: Build macOS
        run: |
          set -o pipefail && xcodebuild test -scheme "OpenAIClient" -destination "platform=macOS,arch=arm64" -skipPackagePluginValidation | xcpretty
      - name: Build macCatalyst
        run: |
          set -o pipefail && xcodebuild test -scheme "OpenAIClient" -destination "platform=macOS,arch=arm64,variant=Mac Catalyst" -skipPackagePluginValidation | xcpretty
      - name: Build tvOS
        run: |
          set -o pipefail && xcodebuild test -scheme "OpenAIClient" -destination "platform=tvOS Simulator,name=Apple TV 4K (3rd generation)" -skipPackagePluginValidation | xcpretty
